const fs = require('fs');
const path = require('path');
const pool = require('../db/db');
const { client: openai, model: AI_MODEL } = require('../utils/openaiClient');
// Free, text-only model (Groq) for translating crop.health's English findings into
// Sinhala — separate quota from the vision model, so it never reintroduces the
// 503 bottleneck.
const { client: textClient, model: TEXT_MODEL } = require('../utils/chatClient');
const { openaiErrorResponse } = require('../utils/openaiError');
const { withAIRetry } = require('../utils/aiRetry');
const { identifyPlant } = require('../utils/plantNetClient');
const { assessHealth, enabled: cropHealthEnabled } = require('../utils/cropHealthClient');
// Detector C: optional custom-trained ML microservice (ml/serve.py).
// Returns null when DISEASE_MODEL_URL is not configured so it is a pure opt-in.
const { classifyDisease, enabled: diseaseModelEnabled } = require('../utils/diseaseModelClient');
// Stage 1: server-side TF.js MobileNetV2 model loaded from server/ml/model/model.json.
// Returns null gracefully when model files are absent.
const { predict: mlPredict } = require('../ml/diseaseModel');
const {
  sanitizeSinhalaDiagnosis,
  getClass35Info,
  getCropClasses35,
  CLASS_35_MAP,
} = require('../utils/diseaseTranslations');

// Build an absolute URL to a stored upload so clients can render the image.
function imageUrl(req, filename) {
  if (!filename) return null;
  return `${req.protocol}://${req.get('host')}/uploads/${filename}`;
}

// Strip markdown fences in case the model wraps its JSON despite instructions.
function parseModelJson(raw) {
  let text = (raw || '').trim();
  if (text.startsWith('```')) {
    text = text.replace(/^```(?:json)?/i, '').replace(/```$/, '').trim();
  }
  return JSON.parse(text);
}

// Map crop.health's 0–1 probability to the High/Medium/Low scale the UI expects.
function toConfidence(probability) {
  if (probability == null) return 'Medium';
  if (probability >= 0.65) return 'High';
  if (probability >= 0.4) return 'Medium';
  return 'Low';
}

// Standardized healthy response for 100% deterministic healthy diagnoses
function getHealthyResponse() {
  return {
    disease_name_en: 'No disease detected',
    disease_name_si: 'රෝගයක් හඳුනාගත නොහැකි විය',
    scientific_name: 'N/A',
    confidence: 'High',
    ml_agrees: true,
    cause: {
      en: 'No pathogen detected. The plant exhibits normal healthy foliage and physiological growth.',
      si: 'රෝග කාරකයක් හඳුනා නොගැනිණි. ශාකය සාමාන්‍ය නිරෝගී පත්‍ර සහ කායික වර්ධනයක් පෙන්නුම් කරයි.',
    },
    why_it_spread: {
      en: 'N/A - Plant is healthy.',
      si: 'අදාළ නොවේ - ශාකය නිරෝගී තත්ත්වයේ පවතී.',
    },
    danger_level: 'Low',
    danger_explanation: {
      en: 'No disease found. Continue regular monitoring.',
      si: 'රෝගයක් හඳුනාගත නොහැකි විය. නිතිපතා අධීක්ෂණය කරන්න.',
    },
    visible_symptoms: {
      en: ['No visible signs of disease or pest damage detected.'],
      si: ['රෝග හෝ කෘමි හානියේ දෘශ්‍ය ලක්ෂණ හඳුනාගත නොහැකි විය.'],
    },
    immediate_action: {
      en: 'No immediate action required. Continue normal crop care.',
      si: 'ක්ෂණික ක්‍රියාමාර්ගයක් අවශ්‍ය නොවේ. සාමාන්‍ය බෝග සත්කාරය දිගටම කරගෙන යන්න.',
    },
    treatment: [],
    what_to_avoid: {
      en: ['Avoid over-fertilizing and waterlogging the soil.'],
      si: ['අධික ලෙස පොහොර යෙදීමෙන් සහ පසෙහි ජලය රඳවා තැබීමෙන් වළකින්න.'],
    },
    prevention_next_season: {
      en: 'Continue monitoring your crop every 3-4 days. Maintain good drainage and appropriate plant spacing.',
      si: 'සෑම දින 3-4 කට වරක් ඔබේ බෝගය නිරීක්ෂණය කරන්න. හොඳ ජලය බැස යාම සහ සුදුසු පරතරය පවත්වා ගන්න.',
    },
    recovery_chance: {
      level: 'Good',
      en: 'Plant appears healthy. Keep monitoring.',
      si: 'ශාකය සෞඛ්‍ය සම්පන්න ලෙස පෙනේ. නිරීක්ෂණය දිගටම කරන්න.',
    },
    when_to_call_officer: {
      en: 'Contact your agricultural officer if you notice any changes or unusual spots in the next 7 days.',
      si: 'ඉදිරි දින 7 තුළ කිසියම් වෙනසක් හෝ අසාමාන්‍ය ලප දුටුවහොත් ඔබේ කෘෂිකර්ම නිලධාරියා අමතන්න.',
    },
    disclaimer_en: 'This diagnosis is generated by AI. Always confirm with a qualified agricultural officer.',
    disclaimer_si: 'මෙය AI ආධාරිත රෝග විනිශ්චයකි. සෑම විටම සුදුසුකම් ලත් කෘෂිකර්ම නිලධාරියෙකු සමඟ සත්‍යාපනය කරන්න.',
  };
}

// --- Detector A: GPT-4o Vision (Stage 2) -----------------------------------
// Two-stage prompt: the ML model result (Step 1) is passed as context.
// Constrained strictly to the 35 classes from class_names.json with temperature: 0
// for 100% deterministic, repeatable diagnoses.
async function detectWithAI(req, plant, crop_type, district, mlResult, class35Info = null) {
  // If the plant is confirmed healthy, return healthy response directly
  if (class35Info && class35Info.is_healthy) {
    return getHealthyResponse();
  }

  const base64Image = fs.readFileSync(req.file.path, { encoding: 'base64' });

  const plantNetHint = plant
    ? `\n      An automated plant-identification system (PlantNet) recognised this plant as ${plant.scientificName || plant.commonName}${plant.commonName ? ` (commonly "${plant.commonName}")` : ''}${plant.organ ? `, photographed organ: ${plant.organ}` : ''}, with a ${plant.scorePct}% match.`
    : '';

  // Candidate classes for this crop among the official 35 classes
  const candidateClasses = getCropClasses35(crop_type);
  const candidateListStr = candidateClasses.map((c) => `"${c.disease_name_en}"`).join(', ');

  let classDirective = '';
  if (class35Info) {
    classDirective = `
OFFICIAL ML CLASSIFICATION (STRICTLY BINDING):
The agricultural ML model has authoritatively identified this ${crop_type} specimen as:
- Class Name: "${class35Info.class_name}"
- English Name: "${class35Info.disease_name_en}"
- Sinhala Name: "${class35Info.disease_name_si}"
- Scientific Name: "${class35Info.scientific_name}"

CRITICAL MANDATORY REQUIREMENT:
The disease is ALREADY DETERMINED. You MUST output EXACTLY:
  "disease_name_en": "${class35Info.disease_name_en}",
  "disease_name_si": "${class35Info.disease_name_si}",
  "scientific_name": "${class35Info.scientific_name}",
  "confidence": "${mlResult && mlResult.confidence >= 70 ? 'High' : mlResult && mlResult.confidence >= 40 ? 'Medium' : 'Low'}",
  "ml_agrees": true

DO NOT change the disease name, do NOT suggest an alternative disease. Your role is exclusively to explain the causes, visible symptoms, spread factors, immediate actions, chemical/organic treatments, dosage, prevention, and Sri Lankan agricultural guidance for "${class35Info.disease_name_en}".`;
  } else {
    classDirective = `
OFFICIAL 35-CLASS REGISTRY REQUIREMENT:
The diagnosis MUST be strictly chosen from one of these recognized classes for ${crop_type}:
${candidateListStr}, or "No disease detected".
Do NOT select any disease outside this official registry.`;
  }

  const prompt = `You are an expert plant pathologist and agricultural advisor
specifically for Sri Lanka. A farmer has uploaded a photo of their
${crop_type} plant from ${district} district, Sri Lanka.
${classDirective}${plantNetHint}

Analyze the image carefully. Then respond ONLY with this exact JSON
structure. No markdown. No extra text. Just the JSON.

Every field must be written in SIMPLE language that a farmer with
no scientific education can understand. Avoid technical jargon.
Use short sentences. Be specific to Sri Lanka.

CRITICAL AGRICULTURAL TRANSLATION RULES:
- Standard Sri Lankan agricultural terminology must be used.
- Plant "rust" disease MUST be "මලකඩ රෝගය" (NEVER translate as "කුකුළු" or "බොජුනේ").
- "Southern rust of corn" MUST be "බඩඉරිඟු වල දක්ෂිණ මලකඩ රෝගය".
- "Blight" MUST be "අංගමාරය", "Spot" MUST be "ලප රෝගය", "Wilt" MUST be "මැලවීම".

{
  "disease_name_en": "Common name of the disease in English, or 'No disease detected'",
  "disease_name_si": "Common name in Sinhala script, or 'රෝගයක් හඳුනාගත නොහැකි විය'",
  "scientific_name": "Scientific name of the pathogen (fungus/bacteria/virus) or 'N/A'",
  "confidence": "High or Medium or Low",
  "ml_agrees": true,

  "cause": {
    "en": "In 2-3 simple sentences: what caused this disease. Example: This disease is caused by a fungus that lives in the soil and spreads through water splashing on leaves. It grows fast when the weather is wet and humid.",
    "si": "Same explanation in Sinhala. Short sentences."
  },

  "why_it_spread": {
    "en": "What conditions made it worse. Example: Heavy rain, poor drainage, planting too close together, not removing old infected leaves.",
    "si": "Same in Sinhala."
  },

  "danger_level": "High or Medium or Low",

  "danger_explanation": {
    "en": "Will it spread to other plants? How fast? What happens if not treated? Give honest assessment in 2 sentences.",
    "si": "Same in Sinhala."
  },

  "visible_symptoms": {
    "en": [
      "First symptom - describe exactly what the farmer can see",
      "Second symptom",
      "Third symptom",
      "Fourth symptom if applicable"
    ],
    "si": [
      "First symptom in Sinhala",
      "Second symptom in Sinhala",
      "Third symptom in Sinhala",
      "Fourth symptom in Sinhala if applicable"
    ]
  },

  "immediate_action": {
    "en": "What the farmer must do RIGHT NOW today, before any spraying. Example: Remove all yellow and brown leaves from the plant and burn them. Do not throw infected leaves on the ground. Stop watering from above - water only at the soil level.",
    "si": "Same in Sinhala."
  },

  "treatment": [
    {
      "step": 1,
      "action_en": "First treatment step - be very specific",
      "action_si": "Same in Sinhala",
      "chemical_en": "Exact chemical name and brand if known. Example: Mancozeb 80% WP (brand: Dithane M-45)",
      "chemical_si": "Same in Sinhala",
      "dose_en": "Exact dose. Example: Mix 2.5 grams per 1 litre of water. Use 10 litres per 100 plants.",
      "dose_si": "Same in Sinhala",
      "when_en": "When to apply. Example: Spray early morning before 8am or after 5pm. Never spray in hot sun.",
      "when_si": "Same in Sinhala"
    },
    {
      "step": 2,
      "action_en": "Second treatment step if needed",
      "action_si": "Same in Sinhala",
      "chemical_en": "Chemical for second spray or 'Same as step 1'",
      "chemical_si": "Same in Sinhala",
      "dose_en": "Repeat dose or adjusted dose",
      "dose_si": "Same in Sinhala",
      "when_en": "Repeat after how many days. Example: Spray again after 7 days if disease is still visible.",
      "when_si": "Same in Sinhala"
    }
  ],

  "what_to_avoid": {
    "en": [
      "Do not do this - common farmer mistake",
      "Do not do this - another mistake",
      "Do not do this"
    ],
    "si": [
      "Same in Sinhala",
      "Same in Sinhala",
      "Same in Sinhala"
    ]
  },

  "prevention_next_season": {
    "en": "2-3 sentences on how to prevent this disease next season. Mention specific resistant varieties available in Sri Lanka if known.",
    "si": "Same in Sinhala."
  },

  "recovery_chance": {
    "level": "Good or Fair or Poor",
    "en": "Honest assessment of whether the plant will recover. Example: If you start treatment today the plant has a good chance of recovery. The new leaves will grow healthy but the infected leaves will not recover.",
    "si": "Same in Sinhala."
  },

  "when_to_call_officer": {
    "en": "Tell the farmer specifically when they MUST contact an agricultural officer. Example: If after 2 rounds of spraying the disease is still spreading, or if more than half the leaves are infected, you must contact your agricultural officer immediately.",
    "si": "Same in Sinhala."
  },

  "disclaimer_en": "This diagnosis is generated by AI based on the photo. The actual disease may differ. Always confirm with a qualified agricultural officer before spending money on chemicals.",
  "disclaimer_si": "මෙය AI ආධාරිත රෝග විනිශ්චයකි. සත්‍ය රෝගය වෙනස් විය හැක. රසායනික ද්‍රව්‍ය මිලදී ගැනීමට පෙර සෑම විටම සුදුසුකම් ලත් කෘෂිකර්ම නිලධාරියෙකු සමඟ සත්‍යාපනය කරන්න."
}

If the image shows a HEALTHY plant with no disease, return:
{
  "disease_name_en": "No disease detected",
  "disease_name_si": "රෝගයක් හඳුනාගත නොහැකි විය",
  "scientific_name": "N/A",
  "confidence": "High",
  "ml_agrees": true,
  "cause": { "en": "N/A", "si": "N/A" },
  "why_it_spread": { "en": "N/A", "si": "N/A" },
  "danger_level": "Low",
  "danger_explanation": {
    "en": "No disease found. Continue regular monitoring.",
    "si": "රෝගයක් හඳුනාගත නොහැකි විය. නිතිපතා අධීක්ෂණය කරන්න."
  },
  "visible_symptoms": {
    "en": ["No visible signs of disease or pest damage detected."],
    "si": ["රෝග හෝ කෘමි හානියේ දෘශ්‍ය ලක්ෂණ හඳුනාගත නොහැකි විය."]
  },
  "immediate_action": {
    "en": "No immediate action required. Continue normal crop care.",
    "si": "ක්ෂණික ක්‍රියාමාර්ගයක් අවශ්‍ය නොවේ. සාමාන්‍ය බෝග සත්කාරය දිගටම කරගෙන යන්න."
  },
  "treatment": [],
  "what_to_avoid": { "en": [], "si": [] },
  "prevention_next_season": {
    "en": "Continue monitoring your crop every 3-4 days. Keep good drainage and avoid overwatering.",
    "si": "සෑම දින 3-4 කට වරක් ඔබේ බෝගය නිරීක්ෂණය කරන්න. හොඳ ජලය බැස යාම පවත්වාගෙන ජලය අධිකව යෙදීමෙන් වළකින්න."
  },
  "recovery_chance": {
    "level": "Good",
    "en": "Plant appears healthy. Keep monitoring.",
    "si": "ශාකය සෞඛ්‍ය සම්පන්න ලෙස පෙනේ. නිරීක්ෂණය දිගටම කරන්න."
  },
  "when_to_call_officer": {
    "en": "Contact your agricultural officer if you notice any changes in the next 7 days.",
    "si": "ඉදිරි දින 7 තුළ කිසිදු වෙනසක් දැකීමේදී ඔබේ කෘෂිකර්ම නිලධාරියා සම්බන්ධ කර ගන්න."
  },
  "disclaimer_en": "This diagnosis is generated by AI. Always confirm with a qualified agricultural officer.",
  "disclaimer_si": "මෙය AI ආධාරිත රෝග විනිශ්චයකි. සෑම විටම සුදුසුකම් ලත් කෘෂිකර්ම නිලධාරියෙකු සමඟ සත්‍යාපනය කරන්න."
}`;

  const completion = await withAIRetry(
    () =>
      openai.chat.completions.create({
        model: AI_MODEL,
        messages: [
          {
            role: 'user',
            content: [
              {
                type: 'image_url',
                image_url: { url: `data:${req.file.mimetype};base64,${base64Image}` },
              },
              {
                type: 'text',
                text: prompt,
              },
            ],
          },
        ],
        temperature: 0,
      }),
    { label: 'disease' }
  );

  const rawJson = parseModelJson(completion.choices[0].message.content);
  let parsed = sanitizeSinhalaDiagnosis(rawJson);

  // Enforce the 35 classes strictly
  if (class35Info) {
    if (class35Info.is_healthy) {
      return getHealthyResponse();
    }
    parsed.disease_name_en = class35Info.disease_name_en;
    parsed.disease_name_si = class35Info.disease_name_si;
    if (class35Info.scientific_name && class35Info.scientific_name !== 'N/A') {
      parsed.scientific_name = class35Info.scientific_name;
    }
    parsed.ml_agrees = true;
  } else {
    const matched = getClass35Info(parsed.disease_name_en);
    if (matched) {
      if (matched.is_healthy) {
        return getHealthyResponse();
      }
      parsed.disease_name_en = matched.disease_name_en;
      parsed.disease_name_si = matched.disease_name_si;
      if (matched.scientific_name && matched.scientific_name !== 'N/A') {
        parsed.scientific_name = matched.scientific_name;
      }
    }
  }

  return sanitizeSinhalaDiagnosis(parsed);
}

// crop.health replies in English only. Translate its findings to Sinhala with the
// free text model so the bilingual UI keeps working. Best-effort — the caller
// falls back to showing English in the Sinhala fields if this throws.
async function translateToSinhala({ disease_name_en, symptoms_en, treatment_en }) {
  const prompt = `Translate the following plant-disease information into natural, fluent Sri Lankan Sinhala.
CRITICAL AGRICULTURAL TRANSLATION RULES:
- Use standard Sri Lankan agricultural terminology.
- "Rust" in plant diseases MUST be translated as "මලකඩ රෝගය" (NEVER translate as poultry/food like "කුකුළු" or "බොජුනේ").
- "Southern rust of corn" MUST be translated as "බඩඉරිඟු වල දක්ෂිණ මලකඩ රෝගය".
- "Blight" MUST be translated as "අංගමාරය".
- "Spot" MUST be translated as "ලප රෝගය".
- "Wilt" MUST be translated as "මැලවීම".

Respond ONLY with valid JSON in this exact format (no markdown, no extra text):
{"disease_name_si":"...","symptoms_si":"...","treatment_si":"..."}

disease_name: ${disease_name_en}
symptoms: ${symptoms_en}
treatment: ${treatment_en}`;

  const completion = await withAIRetry(
    () =>
      textClient.chat.completions.create({
        model: TEXT_MODEL,
        messages: [{ role: 'user', content: prompt }],
      }),
    { label: 'disease-translate' }
  );

  return sanitizeSinhalaDiagnosis(parseModelJson(completion.choices[0].message.content));
}

// --- Detector C: custom-trained ML microservice --------------------------
// Passes the Python FastAPI prediction to the vision LLM (detectWithAI) as a hint
// so the vision model provides structured Sri Lankan guidance for this exact class.
async function buildResultFromModel(req, plant, crop_type, district, pred, mlResult, class35Info = null) {
  if (class35Info && class35Info.is_healthy) {
    return getHealthyResponse();
  }

  try {
    const verifiedResult = await detectWithAI(req, plant, crop_type, district, mlResult, class35Info);
    if (verifiedResult && verifiedResult.disease_name_en) {
      return verifiedResult;
    }
  } catch (err) {
    console.warn('[disease-model] Vision LLM verification failed, falling back to ML translation:', err.message);
  }

  // Fallback: only used if vision LLM is completely unavailable
  const disease_name_en = class35Info
    ? class35Info.disease_name_en
    : pred.isHealthy
    ? 'No disease detected'
    : pred.disease;
  const disease_name_si = class35Info
    ? class35Info.disease_name_si
    : pred.isHealthy
    ? 'රෝගයක් හඳුනාගත නොහැකි විය'
    : disease_name_en;
  const scientific_name = class35Info ? class35Info.scientific_name : 'N/A';

  const symptoms_en = pred.isHealthy
    ? 'No visible signs of disease were detected.'
    : `The trained model identified "${disease_name_en}"${pred.crop ? ` on ${pred.crop}` : ''}.`;
  const treatment_en = pred.isHealthy
    ? 'No treatment needed. Continue good agricultural practices.'
    : 'Consult a local agricultural officer to confirm and obtain a treatment plan.';

  let symptoms_si = symptoms_en;
  let treatment_si = treatment_en;
  try {
    const si = await translateToSinhala({ disease_name_en, symptoms_en, treatment_en });
    symptoms_si = si.symptoms_si || symptoms_si;
    treatment_si = si.treatment_si || treatment_si;
  } catch (err) {
    console.warn('[disease-model] Sinhala translation failed, using English fallback:', err.message);
  }

  return {
    disease_name_en,
    disease_name_si,
    scientific_name,
    confidence: toConfidence(pred.probability),
    ml_agrees: true,
    symptoms_en,
    symptoms_si,
    treatment_en,
    treatment_si,
    disclaimer_en: 'This is an AI-assisted diagnosis. Please verify with a qualified agricultural officer before treatment.',
    disclaimer_si: 'මෙය AI ආධාරිත රෝග විනිශ්චයකි. ප්‍රතිකාර කිරීමට පෙර සුදුසුකම් ලත් කෘෂිකර්ම නිලධාරියෙකු සමඟ සත්‍යාපනය කරන්න.',
  };
}

// --- Detector B: Kindwise crop.health ----------------------------------
// Turns a crop.health result into the same bilingual shape the rest of the
// pipeline (DB insert + client) already expects.
async function buildResultFromCropHealth(health) {
  const disease_name_en = health.isHealthy
    ? 'No disease detected'
    : health.name || 'Unknown condition';
  const symptoms_en =
    health.symptoms ||
    (health.isHealthy ? 'No visible signs of disease were detected.' : '');
  const treatment_en =
    health.treatment ||
    (health.isHealthy
      ? 'No treatment needed. Continue good agricultural practices.'
      : 'Consult a local agricultural officer for a treatment plan.');

  // English defaults for the Sinhala fields; replaced by a translation when one
  // is available, so a rate-limited translator never fails the whole request.
  let disease_name_si = health.isHealthy ? 'රෝගයක් හඳුනාගත නොහැකි විය' : disease_name_en;
  let symptoms_si = symptoms_en;
  let treatment_si = treatment_en;

  try {
    const si = await translateToSinhala({ disease_name_en, symptoms_en, treatment_en });
    disease_name_si = si.disease_name_si || disease_name_si;
    symptoms_si = si.symptoms_si || symptoms_si;
    treatment_si = si.treatment_si || treatment_si;
  } catch (err) {
    console.warn('[crop.health] Sinhala translation failed, using English fallback:', err.message);
  }

  return {
    disease_name_en,
    disease_name_si,
    confidence: toConfidence(health.probability),
    symptoms_en,
    symptoms_si,
    treatment_en,
    treatment_si,
  };
}

// POST /api/disease
async function detect(req, res) {
  const { crop_type, district } = req.body;

  if (!crop_type || !district) {
    return res.status(400).json({ message: 'crop_type and district are required' });
  }
  if (!req.file) {
    return res.status(400).json({ message: 'An image file is required' });
  }

  try {
    // Identify the plant species with PlantNet for the on-screen chip and to
    // ground the AI fallback. Null when disabled or unrecognised.
    const plant = await identifyPlant(req.file.path, req.file.mimetype);

    // -----------------------------------------------------------------------
    // Step 1 — ML microservice inference (Stage 1).
    // Runs on the uploaded image before any external API call.
    // -----------------------------------------------------------------------
    const mlResult = await mlPredict(req.file.path, crop_type);

    // ML column values for the DB — populated from predict() first,
    // then fall back to the browser TF.js hint (tf_label / tf_confidence).
    let mlPrediction = null;  // VARCHAR(200): disease class label
    let mlConfidence = null;  // DECIMAL(5,2): confidence as 0–100 percentage
    let mlClassIndex = null;  // INT: numeric class index
    let class35Info = null;

    if (mlResult) {
      class35Info = getClass35Info(mlResult.className);
      mlPrediction = class35Info ? class35Info.disease_name_en : mlResult.className;
      mlConfidence = mlResult.confidence; // already 0–100 DECIMAL(5,2)
      mlClassIndex = mlResult.classIndex;
    } else if (req.body.tf_label) {
      class35Info = getClass35Info(req.body.tf_label);
      mlPrediction = class35Info ? class35Info.disease_name_en : req.body.tf_label;
      mlConfidence = req.body.tf_confidence
        ? Number(Number(req.body.tf_confidence).toFixed(2))
        : null;
    }

    // -----------------------------------------------------------------------
    // Step 2 — Diagnosis strictly bound to the 35 classes.
    // Three-tier detector chain for the AI step:
    //   C. Custom ML microservice  (DISEASE_MODEL_URL)  — opt-in
    //   B. Kindwise crop.health    (CROP_HEALTH_API_KEY) — opt-in
    //   A. GPT-4o Vision           (always available)    — final fallback
    // -----------------------------------------------------------------------
    let aiResult = null;

    // Fast path: if the Stage 1 ML model detects the plant as healthy, return immediately
    if (class35Info && class35Info.is_healthy) {
      aiResult = getHealthyResponse();
    }

    // Detector C: external ML microservice
    if (!aiResult && diseaseModelEnabled()) {
      const pred = await classifyDisease(req.file.path, req.file.mimetype, crop_type);
      if (pred) {
        if (!class35Info) {
          class35Info = getClass35Info(pred.raw_class_name || pred.className || pred.class_name || pred.disease);
        }
        if (!mlResult) {
          mlPrediction = class35Info ? class35Info.disease_name_en : (pred.disease || mlPrediction);
          mlConfidence = pred.probability != null
            ? Math.round(pred.probability * 10000) / 100
            : mlConfidence;
          mlClassIndex = pred.classIndex != null ? pred.classIndex : mlClassIndex;
          mlResult = {
            className: class35Info ? class35Info.class_name : mlPrediction,
            confidence: mlConfidence,
            classIndex: mlClassIndex,
            top_3: pred.top_3 || [],
          };
        }

        if (class35Info && class35Info.is_healthy) {
          aiResult = getHealthyResponse();
        } else {
          const isModelSupportedCrop = [
            'tomato', 'potato', 'chilli', 'pepper', 'bell pepper',
            'banana', 'corn', 'maize', 'tea', 'rice'
          ].some((c) => crop_type.toLowerCase().includes(c));

          if (isModelSupportedCrop) {
            aiResult = await buildResultFromModel(req, plant, crop_type, district, pred, mlResult, class35Info);
          }
        }
      }
    }

    // Detector B: crop.health.
    if (!aiResult && cropHealthEnabled()) {
      const health = await assessHealth(req.file.path, req.file.mimetype);
      if (health) aiResult = await buildResultFromCropHealth(health);
    }

    // Detector A: GPT-4o Vision — receives the Stage 1 ML result and class35Info as context.
    if (!aiResult) {
      aiResult = await detectWithAI(req, plant, crop_type, district, mlResult, class35Info);
    }

    // Guarantee that if class35Info exists, the diagnosis strictly matches the official 35-class registry
    if (aiResult && class35Info) {
      if (class35Info.is_healthy) {
        aiResult.disease_name_en = 'No disease detected';
        aiResult.disease_name_si = 'රෝගයක් හඳුනාගත නොහැකි විය';
        aiResult.scientific_name = 'N/A';
      } else {
        aiResult.disease_name_en = class35Info.disease_name_en;
        aiResult.disease_name_si = class35Info.disease_name_si;
        if (class35Info.scientific_name && class35Info.scientific_name !== 'N/A') {
          aiResult.scientific_name = class35Info.scientific_name;
        }
      }
      aiResult.ml_agrees = true;
    }

    // Final safety check: sanitize all Sinhala fields against agricultural mistranslations
    if (aiResult) {
      aiResult = sanitizeSinhalaDiagnosis(aiResult);
    }

    // -----------------------------------------------------------------------
    // Step 3 — Persist to disease_reports with ML + AI data.
    // -----------------------------------------------------------------------
    const identifiedSpecies = plant
      ? `${plant.label}${plant.scorePct != null ? ` — ${plant.scorePct}% match` : ''}`
      : null;

    // Map new structured fields to legacy flat columns for backward compatibility.
    const symptomsList = Array.isArray(aiResult.visible_symptoms?.en)
      ? aiResult.visible_symptoms.en.join(', ')
      : (aiResult.symptoms_en || '');
    const treatmentEnFlat = Array.isArray(aiResult.treatment)
      ? aiResult.treatment.map(t => t.action_en).filter(Boolean).join('. ')
      : (aiResult.treatment_en || '');
    const treatmentSiFlat = Array.isArray(aiResult.treatment)
      ? aiResult.treatment.map(t => t.action_si).filter(Boolean).join('. ')
      : (aiResult.treatment_si || '');

    const [insert] = await pool.query(
      `INSERT INTO disease_reports
       (user_id, crop_type, district, image_path, identified_species,
        disease_name, confidence_level, symptoms, treatment_en, treatment_si,
        ml_prediction, ml_confidence, ml_class_index, full_result)
       VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)`,
      [
        req.user.id,
        crop_type,
        district,
        req.file.filename,
        identifiedSpecies,
        aiResult.disease_name_en,
        aiResult.confidence,
        symptomsList,
        treatmentEnFlat,
        treatmentSiFlat,
        mlPrediction,
        mlConfidence,
        mlClassIndex,
        JSON.stringify(aiResult),
      ]
    );

    await pool.query(
      `INSERT INTO notifications (user_id, type, message, related_id)
       VALUES (?, 'disease_result', ?, ?)`,
      [
        req.user.id,
        `Disease detection complete: ${aiResult.disease_name_en} identified in your ${crop_type}.`,
        insert.insertId,
      ]
    );

    // -----------------------------------------------------------------------
    // Step 4 — Return combined result.
    // ml_result: instant Stage 1 classification.
    // ai_result: full bilingual GPT-4o diagnosis (including disclaimer).
    // -----------------------------------------------------------------------
    return res.json({
      report_id: insert.insertId,
      image_url: imageUrl(req, req.file.filename),
      plantnet: plant,
      ml_label: mlPrediction,
      ml_confidence: mlConfidence,
      top_3: mlResult?.top_3 || null,
      ml_result: mlResult
        ? {
            className: mlResult.className,
            confidence: mlResult.confidence,
            classIndex: mlResult.classIndex,
            top_3: mlResult.top_3,
          }
        : mlPrediction
        ? { className: mlPrediction, confidence: mlConfidence, classIndex: mlClassIndex }
        : null,
      ai_result: aiResult,
      // Legacy flat fields kept for backward compatibility
      disease_name_en: aiResult.disease_name_en,
      disease_name_si: aiResult.disease_name_si,
      confidence: aiResult.confidence,
      symptoms_en: symptomsList,
      symptoms_si: Array.isArray(aiResult.visible_symptoms?.si)
        ? aiResult.visible_symptoms.si.join(', ')
        : (aiResult.symptoms_si || ''),
      treatment_en: treatmentEnFlat,
      treatment_si: treatmentSiFlat,
      disclaimer_en:
        aiResult.disclaimer_en ||
        'This diagnosis is generated by AI. Always confirm with a qualified agricultural officer.',
      disclaimer_si:
        aiResult.disclaimer_si ||
        '\u0db8\u0dd9\u0dba AI \u0d86\u0daf\u0dc4\u0dcf\u0dbb\u0dd2\u0dad \u0dbb\u0ddd\u0d9c \u0dc5\u0dd2\u0db1\u0dd2\u0DC1\u0dca\u0d91\u0dba\u0d9a\u0dd2.',
    });
  } catch (err) {
    console.error('detect error:', err.status ?? '', err.code ?? '', err.message);
    const { status, message } = openaiErrorResponse(err, 'Could not analyze image, please try again');
    return res.status(status).json({ message });
  }
}

// POST /api/disease/share
async function shareWithOfficer(req, res) {
  const { report_id, officer_id } = req.body;

  if (!report_id || !officer_id) {
    return res.status(400).json({ message: 'report_id and officer_id are required' });
  }

  try {
    const [reports] = await pool.query(
      'SELECT * FROM disease_reports WHERE id = ? AND user_id = ?',
      [report_id, req.user.id]
    );
    const report = reports[0];
    if (!report) {
      return res.status(404).json({ message: 'Report not found' });
    }

    await pool.query(
      'UPDATE disease_reports SET shared_with_officer = 1, officer_id = ? WHERE id = ?',
      [officer_id, report_id]
    );

    await pool.query(
      `INSERT INTO notifications (user_id, type, message, related_id)
       VALUES (?, 'disease_shared', ?, ?)`,
      [
        officer_id,
        `A farmer shared a disease report for ${report.crop_type} in ${report.district} for your review.`,
        report_id,
      ]
    );

    return res.json({ success: true });
  } catch (err) {
    console.error('shareWithOfficer error:', err.message);
    return res.status(500).json({ message: 'Server error' });
  }
}

// GET /api/disease/history
async function getHistory(req, res) {
  try {
    const [reports] = await pool.query(
      'SELECT * FROM disease_reports WHERE user_id = ? ORDER BY created_at DESC',
      [req.user.id]
    );
    const withUrls = reports.map((r) => {
      let parsed_result = null;
      if (r.full_result) {
        try {
          parsed_result = JSON.parse(r.full_result);
        } catch (_) {
          parsed_result = null;
        }
      }
      return { ...r, image_url: imageUrl(req, r.image_path), parsed_result };
    });
    return res.json({ reports: withUrls });
  } catch (err) {
    console.error('getHistory error:', err.message);
    return res.status(500).json({ message: 'Server error' });
  }
}

// GET /api/disease/:id
async function getReport(req, res) {
  const reportId = req.params.id;

  try {
    const [reports] = await pool.query('SELECT * FROM disease_reports WHERE id = ?', [
      reportId,
    ]);
    const report = reports[0];
    if (!report) {
      return res.status(404).json({ message: 'Report not found' });
    }

    // Accessible by the owner, or the officer the report was shared with.
    const isOwner = report.user_id === req.user.id;
    const isAssignedOfficer = report.officer_id === req.user.id;
    if (!isOwner && !isAssignedOfficer) {
      return res.status(403).json({ message: 'Access denied' });
    }

    // Parse full_result JSON if present (new structured format), null for legacy reports.
    let parsed_result = null;
    if (report.full_result) {
      try {
        parsed_result = JSON.parse(report.full_result);
      } catch (_) {
        parsed_result = null;
      }
    }

    return res.json({
      report: {
        ...report,
        image_url: imageUrl(req, report.image_path),
        parsed_result,
      },
    });
  } catch (err) {
    console.error('getReport error:', err.message);
    return res.status(500).json({ message: 'Server error' });
  }
}

// PATCH /api/disease/:id/reviewed  (officer only)
async function markReviewed(req, res) {
  const reportId = req.params.id;

  try {
    const [reports] = await pool.query('SELECT * FROM disease_reports WHERE id = ?', [
      reportId,
    ]);
    const report = reports[0];
    if (!report) {
      return res.status(404).json({ message: 'Report not found' });
    }
    if (report.officer_id !== req.user.id) {
      return res.status(403).json({ message: 'This report was not shared with you' });
    }

    await pool.query("UPDATE disease_reports SET status = 'reviewed' WHERE id = ?", [
      reportId,
    ]);

    await pool.query(
      `INSERT INTO notifications (user_id, type, message, related_id)
       VALUES (?, 'disease_reviewed', ?, ?)`,
      [
        report.user_id,
        `An officer reviewed your disease report for ${report.crop_type}.`,
        reportId,
      ]
    );

    return res.json({ success: true });
  } catch (err) {
    console.error('markReviewed error:', err.message);
    return res.status(500).json({ message: 'Server error' });
  }
}

// DELETE /api/disease/:id
// Farmers can only delete their own reports. The uploaded image file is also
// removed from disk so orphaned files don't accumulate.
async function deleteReport(req, res) {
  const reportId = req.params.id;

  try {
    // Fetch the row first so we can verify ownership and get the image path.
    const [rows] = await pool.query(
      'SELECT user_id, image_path FROM disease_reports WHERE id = ?',
      [reportId]
    );
    const report = rows[0];

    if (!report) {
      return res.status(404).json({ message: 'Report not found' });
    }
    if (report.user_id !== req.user.id) {
      return res.status(403).json({ message: 'Forbidden' });
    }

    // Remove the image file from disk (best-effort — don't fail if missing).
    if (report.image_path) {
      const imgPath = path.join(__dirname, '..', 'uploads', report.image_path);
      try { fs.unlinkSync(imgPath); } catch (_) { /* ignore */ }
    }

    // Cascade: delete related shared_reports rows first (FK), then the report.
    await pool.query('DELETE FROM shared_reports WHERE report_id = ?', [reportId]);
    await pool.query('DELETE FROM disease_reports WHERE id = ?', [reportId]);

    return res.json({ message: 'Report deleted successfully' });
  } catch (err) {
    console.error('deleteReport error:', err.message);
    return res.status(500).json({ message: 'Server error' });
  }
}

module.exports = {
  detect,
  shareWithOfficer,
  getHistory,
  getReport,
  markReviewed,
  deleteReport,
};
