// Agro-ecological context for each of Sri Lanka's 25 districts.
// Injected into the AI system prompt so the chatbot gives grounded,
// district-specific advice instead of generic Sri Lanka recommendations.

const DISTRICT_CONTEXT = {
  Ampara: {
    zone: 'Dry zone',
    rainfall: '1,500–2,000 mm/year (mainly north-east monsoon, Oct–Jan)',
    elevation: 'Lowland (0–300 m)',
    soils: 'Reddish-brown earths; alluvial soils in Gal Oya river plains',
    mainCrops: ['Rice (paddy)', 'Sugarcane', 'Vegetables', 'Maize', 'Sesame'],
    seasons: 'Maha (Oct–Mar) is the main paddy season; Yala (Apr–Sep) depends on irrigation',
    challenges: 'Drought stress during Yala, flooding near Gal Oya, stem borer and brown planthopper (BPH) in paddy',
    irrigation: 'Gal Oya and Ampara irrigation schemes',
    notes: 'Major rice district; sugarcane at Hingurana; multi-ethnic farming community',
  },
  Anuradhapura: {
    zone: 'Dry zone',
    rainfall: '1,000–1,500 mm/year (north-east monsoon dominates)',
    elevation: 'Lowland plain (50–150 m)',
    soils: 'Reddish-brown earths; low-humic gley soils in tank-irrigated areas',
    mainCrops: ['Rice (paddy)', 'Chilli', 'Onions', 'Green gram', 'Maize', 'Sesame', 'Groundnut'],
    seasons: 'Maha (Oct–Mar) and Yala (Apr–Sep); both viable with tank irrigation',
    challenges: 'Prolonged dry spells, blast and sheath blight in paddy, thrips and mites on chilli',
    irrigation: 'Ancient wewa (tank) irrigation; Mahaweli System B and C',
    notes: 'Largest district; ancient irrigation civilisation; major food crop granary',
  },
  Badulla: {
    zone: 'Intermediate to highland',
    rainfall: '1,500–2,500 mm/year (receives both monsoons)',
    elevation: '600–2,300 m (highly variable)',
    soils: 'Red-yellow podzolic; mountain regosols at high elevations',
    mainCrops: ['Tea', 'Potato', 'Cabbage', 'Leeks', 'Beans', 'Paddy (low elevations)'],
    seasons: 'Year-round vegetable cultivation; tea is perennial; paddy Maha and Yala at lower elevations',
    challenges: 'Soil erosion on steep slopes, late blight of potato, blister blight of tea, cold snap damage',
    irrigation: 'Mainly rainfed; small irrigation schemes at low elevations',
    notes: 'Ella and Bandarawela are highland vegetable hubs; important tea district',
  },
  Batticaloa: {
    zone: 'Dry zone (east coast)',
    rainfall: '1,500–2,000 mm/year (mainly north-east monsoon)',
    elevation: 'Coastal lowland (0–100 m)',
    soils: 'Sandy coastal soils; alluvial in lagoon areas',
    mainCrops: ['Rice (paddy)', 'Vegetables', 'Coconut', 'Banana'],
    seasons: 'Maha (Oct–Mar) main paddy season; Yala limited by water',
    challenges: 'Saltwater intrusion in coastal fields, cyclone risk, blast and BPH in paddy',
    irrigation: 'Batticaloa lagoon-area irrigation schemes',
    notes: 'Coastal district; traditional paddy farming; fisheries important',
  },
  Colombo: {
    zone: 'Wet zone',
    rainfall: '2,000–2,500 mm/year (south-west monsoon May–Sep; inter-monsoonal Oct–Nov)',
    elevation: 'Near sea level (0–30 m)',
    soils: 'Lateritic and alluvial soils near Kelani river',
    mainCrops: ['Leafy vegetables', 'Home garden crops', 'Coconut', 'Fruits'],
    seasons: 'Year-round cultivation; no distinct Maha/Yala due to wet climate',
    challenges: 'Urban waterlogging, limited arable land, soil contamination, high pest pressure in peri-urban gardens',
    irrigation: 'Rainfall usually sufficient; Kelani river water for some areas',
    notes: 'Mainly urban/peri-urban home garden farming; limited commercial agriculture',
  },
  Galle: {
    zone: 'Wet zone (southern coast)',
    rainfall: '2,000–3,000 mm/year (south-west monsoon dominant)',
    elevation: 'Coastal to hill (0–500 m)',
    soils: 'Red-yellow podzolic; alluvial near rivers',
    mainCrops: ['Tea', 'Rubber', 'Cinnamon', 'Coconut', 'Clove', 'Nutmeg'],
    seasons: 'Perennial crops dominate; paddy in low areas during Maha',
    challenges: 'High humidity favouring fungal diseases (black rot of cinnamon, Phytophthora in rubber), coastal salinity',
    irrigation: 'Predominantly rainfed',
    notes: 'World-renowned for true Ceylon cinnamon; export spice production hub',
  },
  Gampaha: {
    zone: 'Wet zone',
    rainfall: '1,800–2,300 mm/year (south-west monsoon)',
    elevation: 'Low plain (0–50 m)',
    soils: 'Reddish-brown lateritic; some alluvial',
    mainCrops: ['Rubber', 'Coconut', 'Vegetables', 'Paddy (minor)'],
    seasons: 'Year-round for most crops; Maha for paddy',
    challenges: 'Root rot and white root disease in rubber, weed pressure, rapid urban encroachment on farmland',
    irrigation: 'Mainly rainfed',
    notes: 'Densely populated peri-urban district; agricultural land rapidly urbanising',
  },
  Hambantota: {
    zone: 'Dry zone (semi-arid south)',
    rainfall: '900–1,200 mm/year (one of the driest districts)',
    elevation: 'Coastal plain to rolling hills (0–300 m)',
    soils: 'Reddish-brown earths; sandy soils near coast',
    mainCrops: ['Rice (paddy)', 'Sesame', 'Chilli', 'Vegetables', 'Banana', 'Mango'],
    seasons: 'Maha (Oct–Mar) is the main season; Yala marginal without irrigation',
    challenges: 'Severe drought, high evapotranspiration, salt wind damage, chronic water scarcity',
    irrigation: 'Ridiyagama reservoir; minor irrigation tanks',
    notes: 'Driest district; sesame and chilli are well-adapted drought-tolerant crops here',
  },
  Jaffna: {
    zone: 'Arid / Dry zone',
    rainfall: '900–1,200 mm/year (north-east monsoon Nov–Jan; very dry rest of year)',
    elevation: 'Flat peninsula at sea level',
    soils: 'Limestone-derived soils; sandy, low organic matter; prone to salinity',
    mainCrops: ['Red onions', 'Chilli', 'Brinjal', 'Okra', 'Tobacco', 'Mango', 'Nelli (gooseberry)', 'Palmyra palm'],
    seasons: 'Yala (Apr–Sep) main vegetable season using well irrigation; Maha for paddy',
    challenges: 'Groundwater over-extraction, saltwater intrusion, cyclone risk, extreme dry-season heat',
    irrigation: 'Groundwater wells (dug and tube wells); Iranamadu tank',
    notes: 'Famous for premium Jaffna red onions (export quality); intensive well-irrigation vegetable farming; palmyra products',
  },
  Kalutara: {
    zone: 'Wet zone',
    rainfall: '2,000–3,000 mm/year',
    elevation: 'Coastal to hilly (0–300 m)',
    soils: 'Lateritic red-yellow podzolic',
    mainCrops: ['Rubber', 'Coconut', 'Cinnamon', 'Mangosteen', 'Paddy'],
    seasons: 'Perennial crops year-round; Maha paddy in low-lying areas',
    challenges: 'Phytophthora root rot in rubber and cinnamon, waterlogging in paddy',
    irrigation: 'Rainfed',
    notes: 'Mangosteen and exotic fruit production; high-rainfall suitable for rubber and spices',
  },
  Kandy: {
    zone: 'Wet zone (central highlands)',
    rainfall: '1,800–2,500 mm/year (both monsoons)',
    elevation: '400–2,000 m',
    soils: 'Red-yellow podzolic; mountain regosols at higher elevations',
    mainCrops: ['Tea', 'Cardamom', 'Pepper', 'Clove', 'Vegetables', 'Paddy (lower areas)', 'Coconut'],
    seasons: 'Tea and spices year-round; paddy Maha and Yala; vegetables year-round',
    challenges: 'Landslide risk on steep slopes, blister blight and grey blight in tea, soil erosion',
    irrigation: 'Primarily rainfed; some Mahaweli-fed irrigation at lower elevations',
    notes: 'Cultural capital; Tea Research Institute (TRI) located here; highland spice belt',
  },
  Kegalle: {
    zone: 'Wet zone',
    rainfall: '2,000–3,000 mm/year',
    elevation: '100–1,000 m',
    soils: 'Red-yellow podzolic; some alluvial',
    mainCrops: ['Rubber', 'Tea', 'Coconut', 'Vegetables', 'Paddy'],
    seasons: 'Perennial crops year-round; Maha and Yala paddy',
    challenges: 'White root disease in rubber, collar rot in tea nurseries, soil erosion on hillsides',
    irrigation: 'Mostly rainfed',
    notes: 'Rubber smallholder belt; rubber-tea transition zone',
  },
  Kilinochchi: {
    zone: 'Dry zone',
    rainfall: '1,000–1,300 mm/year (north-east monsoon)',
    elevation: 'Flat lowland (0–100 m)',
    soils: 'Reddish-brown earths; alluvial near Iranamadu tank',
    mainCrops: ['Rice (paddy)', 'Vegetables', 'Chilli', 'Maize'],
    seasons: 'Maha primary; Yala with Iranamadu tank water',
    challenges: 'Drought, soil degradation, ongoing post-conflict rehabilitation of irrigation infrastructure',
    irrigation: 'Iranamadu tank; small traditional tanks',
    notes: 'Recovering agricultural district post-civil conflict; significant rehabilitation ongoing',
  },
  Kurunegala: {
    zone: 'Intermediate zone',
    rainfall: '1,200–1,800 mm/year (both monsoons)',
    elevation: '60–500 m',
    soils: 'Reddish-brown earths to red-yellow podzolic',
    mainCrops: ['Coconut', 'Rubber', 'Paddy', 'Vegetables', 'Pineapple', 'Maize'],
    seasons: 'Maha and Yala paddy; perennial crops year-round',
    challenges: 'Weligama coconut leaf wilt disease, mite damage on coconut, blast in paddy',
    irrigation: 'Deduru Oya irrigation; Mahaweli System H; small tank cascade',
    notes: 'Largest coconut-producing district; centre of the coconut triangle; diversified farming',
  },
  Mannar: {
    zone: 'Arid / Dry zone',
    rainfall: '900–1,100 mm/year (very erratic)',
    elevation: 'Flat island and coastal plain (0–50 m)',
    soils: "Sandy, low fertility; alluvial near Giant's Tank",
    mainCrops: ['Onions', 'Vegetables', 'Paddy (minor)', 'Palmyra palm'],
    seasons: 'North-east monsoon (Maha) is the primary growing season',
    challenges: "Severe drought, strong desiccating sea winds, limited freshwater, salt spray damage",
    irrigation: "Giant's Tank irrigation scheme; groundwater wells",
    notes: "Arid conditions; onion production; Giant's Tank paddy scheme; significant fishing community",
  },
  Matale: {
    zone: 'Intermediate zone',
    rainfall: '1,500–2,000 mm/year',
    elevation: '150–1,500 m',
    soils: 'Reddish-brown earths; red-yellow podzolic at higher elevations',
    mainCrops: ['Vegetables', 'Paddy', 'Tobacco', 'Spices', 'Tea (higher areas)'],
    seasons: 'Maha and Yala paddy; vegetables year-round at various elevations',
    challenges: 'Variable rainfall between seasons, leaf curl virus in tobacco, erosion on hillside farms',
    irrigation: 'Mahaweli System C; Nalanda and Sigiriya area schemes',
    notes: 'Dambulla Dedicated Economic Centre is the largest vegetable wholesale market in Sri Lanka',
  },
  Matara: {
    zone: 'Wet zone (southern coast)',
    rainfall: '2,000–2,500 mm/year',
    elevation: 'Coastal to mid-elevation (0–600 m)',
    soils: 'Red-yellow podzolic; alluvial coastal soils',
    mainCrops: ['Rubber', 'Coconut', 'Cinnamon', 'Paddy', 'Vegetables'],
    seasons: 'Perennial crops year-round; Maha paddy in low-lying areas',
    challenges: 'Phytophthora in rubber, bark borer in coconut, flooding risk in low-lying paddy areas',
    irrigation: 'Mainly rainfed',
    notes: 'Southern coast; cinnamon export; tourism growing alongside agriculture',
  },
  Monaragala: {
    zone: 'Dry zone (south-east)',
    rainfall: '1,000–1,500 mm/year (erratic)',
    elevation: '50–500 m (undulating terrain)',
    soils: 'Reddish-brown earths; shallow gravelly soils on ridges',
    mainCrops: ['Paddy', 'Maize', 'Chilli', 'Sesame', 'Vegetables', 'Honey (forest areas)'],
    seasons: 'Maha (Oct–Mar) is the primary season; Yala marginal without irrigation',
    challenges: 'Erratic rainfall, severe drought years, crop losses from wild elephant intrusions, limited irrigation',
    irrigation: 'Uma Oya project (ongoing); small village tanks',
    notes: 'Remote district with active elephant corridors; organic farming potential; chronic food insecurity in some areas',
  },
  Mullaitivu: {
    zone: 'Dry zone',
    rainfall: '1,200–1,500 mm/year (north-east monsoon)',
    elevation: 'Coastal flat (0–100 m)',
    soils: 'Sandy coastal; some alluvial',
    mainCrops: ['Paddy', 'Vegetables', 'Coconut'],
    seasons: 'Maha (Oct–Mar) primary; Yala limited',
    challenges: 'Post-conflict infrastructure gaps, coastal salinity, limited market access',
    irrigation: 'Small tanks; rehabilitation projects ongoing',
    notes: 'Post-conflict recovery; fisheries alongside agriculture; remote coastal farming communities',
  },
  'Nuwara Eliya': {
    zone: 'Highland (wet)',
    rainfall: '2,000–2,500 mm/year; peaks above 3,000 mm at highest elevations',
    elevation: '1,200–2,524 m (highest district in Sri Lanka)',
    soils: 'Mountain regosols; peat soils at highest elevations; red-yellow podzolic on slopes',
    mainCrops: ['Tea', 'Potato', 'Cabbage', 'Leeks', 'Carrot', 'Beans', 'Strawberry', 'Cut flowers'],
    seasons: 'Year-round vegetable and tea cultivation; cold season (Nov–Feb) reduces growth rates',
    challenges: 'Late blight on potato, damping-off in seedlings, frost risk above 2,000 m, severe soil erosion on terraces, blister blight in tea',
    irrigation: 'Mainly rainfed; cool temperatures keep evapotranspiration low',
    notes: "Coldest district; temperatures can drop to 0°C; premier Ceylon high-grown tea; Sri Lanka's main highland vegetable basket",
  },
  Polonnaruwa: {
    zone: 'Dry zone',
    rainfall: '1,000–1,500 mm/year (north-east monsoon)',
    elevation: '50–150 m',
    soils: 'Reddish-brown earths; alluvial near major tanks',
    mainCrops: ['Rice (paddy)', 'Sugarcane', 'Vegetables', 'Maize', 'Banana'],
    seasons: 'Maha and Yala both viable with Mahaweli irrigation',
    challenges: 'Water distribution equity, blast and brown planthopper in paddy, CKDu (chronic kidney disease of unknown etiology) linked to local water quality',
    irrigation: 'Mahaweli System B and H; ancient Parakrama Samudra tank',
    notes: 'Key rice granary; Mahaweli irrigation hub; ancient hydraulic civilisation heritage',
  },
  Puttalam: {
    zone: 'Dry zone',
    rainfall: '900–1,200 mm/year',
    elevation: 'Coastal flat to low plain (0–100 m)',
    soils: 'Sandy coastal soils; reddish-brown earths inland',
    mainCrops: ['Coconut', 'Onions', 'Vegetables', 'Paddy', 'Prawns/Salt (coastal)'],
    seasons: 'North-east monsoon (Maha) primary for crops; Yala limited',
    challenges: 'Drought, saltwater intrusion into wells, rhinoceros beetle and coconut mite, sand dune encroachment',
    irrigation: 'North-west irrigation project; groundwater wells',
    notes: 'Northern coconut production zone; solar salt flats; Wilpattu buffer zone farming',
  },
  Ratnapura: {
    zone: 'Wet zone',
    rainfall: '3,000–4,500 mm/year (among the highest in Sri Lanka)',
    elevation: '50–2,000 m',
    soils: 'Red-yellow podzolic; alluvial in Kalu Ganga plains',
    mainCrops: ['Rubber', 'Tea (higher elevations)', 'Paddy', 'Rambutan', 'Durian', 'Vegetables'],
    seasons: 'Year-round due to near-constant high rainfall; Maha paddy dominant',
    challenges: 'Phytophthora in rubber and rambutan, frequent flooding and landslides, waterlogging in paddy, pest pressure year-round',
    irrigation: 'Rainfed (excess rainfall is often the challenge, not drought)',
    notes: 'Gem capital; highest annual rainfall; rambutan and durian production; flood management is critical',
  },
  Trincomalee: {
    zone: 'Dry zone (east coast)',
    rainfall: '1,500–2,000 mm/year (north-east monsoon dominant)',
    elevation: 'Coastal to hilly (0–300 m)',
    soils: 'Alluvial near rivers; reddish-brown earths inland',
    mainCrops: ['Paddy', 'Vegetables', 'Coconut', 'Cashew', 'Sugarcane'],
    seasons: 'Maha primary paddy season; Yala with Kantalai tank water',
    challenges: 'Blast in paddy, seasonal water scarcity during Yala, crop damage by wild elephants',
    irrigation: 'Kantalai tank; Mahaweli System; smaller tank cascade',
    notes: 'Natural deep-water harbour city; cashew production; multi-ethnic farming landscape',
  },
  Vavuniya: {
    zone: 'Dry zone',
    rainfall: '1,000–1,300 mm/year',
    elevation: 'Interior flat plain (80–200 m)',
    soils: 'Reddish-brown earths',
    mainCrops: ['Paddy', 'Vegetables', 'Maize', 'Onions', 'Green gram'],
    seasons: 'Maha primary; Yala limited without supplementary irrigation',
    challenges: 'Drought, limited market infrastructure, post-conflict land rehabilitation',
    irrigation: "Small irrigation tanks; some feeds from Giant's Tank command area",
    notes: 'Gateway to northern province; recovering agricultural sector; strategic crossroads district',
  },
};

function getDistrictContext(district) {
  return DISTRICT_CONTEXT[district] || null;
}

module.exports = { getDistrictContext };
